export const Line = [
     'For men', 
     'For Women',
     'Velvet',
     'DEVOTION',
     'BLUE JASMINE',
     'DOLCE',
     'GARDEN',
     'LILY',
     'PEONY',
     'ROSE',
     'SHINE',
     'VIOLET',
     'K BY DG',
     'Q BY DG',
     'LB eau inten',
     'LB for men',
     'Light Blue',
     'Limperatri',
     'For Men Gold',
     'The One',
     'The One Gold',
     'The Only One',
     'Limperatrice',
     'Face Blush',
     'Brownliner',
     'Eye Mascara',
     'Face pwdr',
     'Liquid Lipstick',
     'Eye Brush',
     'Face Brush',
     'Eyeliner',
     'Feline Eyeshw Qua',
     'Eyeshw stick',
     'Brow Pencil',
     'Lip Brush',
     'Lip Definer',
     'Lip Pencil',
     'Facial Moisturizer',
     'Skin Concealer',
     'Foundation',
     'Lip Treatment',
     'Face Fdt',
     'Styling Gel',
     
     ];
     