export const ProductCategories = [
     'Classic', 
'Collection', 
'DEVOTION', 
'DOLCE', 
'K&Q', 
'Light Blue', 
'Limperatrice', 
'The one', 
'Blush', 
'Brow', 
'DEVOTION MUP', 
'Dolcissimo', 
'Eye Applicator', 
'Face Applicator', 
'FELIN EYE', 
'Intenseyes', 
'Khol', 
'Lip Applicator', 
'Lip Liner', 
'Millennialskin', 
'PASSIONEYES', 
'Perfect', 
'Secret', 
'Sheerlips', 
'Shinissimo', 
'Solar Glow', 
'The Only One', 
'The Only one Sheer', 
'Velvetskin',
]