export const 
ProductLines = [
{  groupLine: 'Classic', line: 'For men'},
{  groupLine: 'Classic', line: 'For Women'},
{  groupLine: 'Collection', line: 'Velvet'},
{  groupLine: 'DEVOTION', line: 'DEVOTION'},
{  groupLine: 'DOLCE', line: 'BLUE JASMINE'},
{  groupLine: 'DOLCE', line: 'DOLCE'},
{  groupLine: 'DOLCE', line: 'GARDEN'},
{  groupLine: 'DOLCE', line: 'LILY'},
{  groupLine: 'DOLCE', line: 'PEONY'},
{  groupLine: 'DOLCE', line: 'ROSE'},
{  groupLine: 'DOLCE', line: 'SHINE'},
{  groupLine: 'DOLCE', line: 'VIOLET'},
{  groupLine: 'K&Q', line: 'K BY DG'},
{  groupLine: 'K&Q', line: 'Q BY DG'},
{  groupLine: 'Light Blue', line: 'LB eau inten'},
{  groupLine: 'Light Blue', line: 'LB for men'},
{  groupLine: 'Light Blue', line: 'Light Blue'},
{  groupLine: 'Limperatrice', line: 'Limperatri'},
{  groupLine: 'The one', line: 'For Men'},
{  groupLine: 'The one', line: 'For Men Gold'},
{  groupLine: 'The one', line: 'The One'},
{  groupLine: 'The one', line: 'The One Gold'},
{  groupLine: 'The one', line: 'The Only One'},
{  groupLine: 'Limperatrice', line: 'Limperatrice'},
{  groupLine: 'Blush', line: 'Face Blush'},
{  groupLine: 'Brow', line: 'Brownliner'},
{  groupLine: 'DEVOTION MUP', line: 'Eye Mascara'},
{  groupLine: 'DEVOTION MUP', line: 'Face pwdr'},
{  groupLine: 'DEVOTION MUP', line: 'Liquid Lipstick'},
{  groupLine: 'Dolcissimo', line: 'Liquid Lipstick'},
{  groupLine: 'Eye Applicator', line: 'Eye Brush'},
{  groupLine: 'Face Applicator', line: 'Face Brush'},
{  groupLine: 'FELIN EYE', line: 'Eyeliner'},
{  groupLine: 'FELIN EYE', line: 'Feline Eyeshw Qua'},
{  groupLine: 'Intenseyes', line: 'Eyeshw stick'},
{  groupLine: 'Khol', line: 'Brow Pencil'},
{  groupLine: 'Lip Applicator', line: 'Lip Brush'},
{  groupLine: 'Lip Liner', line: 'Lip Definer'},
{  groupLine: 'Lip Liner', line: 'Lip Pencil'},
{  groupLine: 'Millennialskin', line: 'Facial Moisturizer'},
{  groupLine: 'Millennialskin', line: 'Skin Concealer'},
{  groupLine: 'PASSIONEYES', line: 'Eye Mascara'},
{  groupLine: 'Perfect', line: 'Foundation'},
{  groupLine: 'Secret', line: 'Facial Moisturizer'},
{  groupLine: 'Sheerlips', line: 'Lip Treatment'},
{  groupLine: 'Shinissimo', line: 'Liquid Lipstick'},
{  groupLine: 'Solar Glow', line: 'Face Fdt'},
{  groupLine: 'Solar Glow', line: 'Face pwdr'},
{  groupLine: 'Solar Glow', line: 'Foundation'},
{  groupLine: 'Solar Glow', line: 'Styling Gel'},
{  groupLine: 'The Only One', line: 'Lip Treatment'},
{  groupLine: 'The Only one Sheer', line: 'Lip Treatment'},
{  groupLine: 'Velvetskin', line: 'Foundation'},

]